### ISSUE TITLE
[BUG] /profile-data error

### ISSUE THREAD

**Issue by RicBent** [migaku-official/Migaku-Anki-Extension#15]
Access to /profile-data crashes seemingly in the time span between Anki open and profile load.

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-12-29 12:20:55

ERROR:tornado.application:Uncaught exception POST /profile-data (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:44432', method='POST', uri='/profile-data', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "C:\Users\kontr\AppData\Roaming\Anki2\addons21\Migaku Anki Extension\lib\shared\tornado\web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "C:\Users\kontr\AppData\Roaming\Anki2\addons21\Migaku Anki Extension\migaku_connection\profile_data_provider.py", line 18, in post
    profile_data = self.compose_profile_data()
  File "C:\Users\kontr\AppData\Roaming\Anki2\addons21\Migaku Anki Extension\migaku_connection\profile_data_provider.py", line 28, in compose_profile_data
    profile_data['decks'] =  self.compose_deck_data()
  File "C:\Users\kontr\AppData\Roaming\Anki2\addons21\Migaku Anki Extension\migaku_connection\profile_data_provider.py", line 39, in compose_deck_data
    for deck in aqt.mw.col.decks.all()
AttributeError: 'NoneType' object has no attribute 'decks'
ERROR:tornado.access:500 POST /profile-data (127.0.0.1) 2.00ms
ERROR:tornado.application:Uncaught exception POST /profile-data (127.0.0.1)```

**Comment by RicBent** [comment]
Fixed with 442bf4ab90b9d047178e7513dbf52b299afc0a28
