### ISSUE TITLE
[BUG] Error when adding definitions to card add dialog

### ISSUE THREAD

**Issue by RicBent** [migaku-official/Migaku-Anki-Extension#22]
```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-01-31 14:31:26

ERROR:tornado.application:Uncaught exception POST /create (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:44432', method='POST', uri='/create', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\Migaku Anki Extension\lib\shared\tornado\web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\Migaku Anki Extension\migaku_connection\card_creator.py", line 52, in post
    self.handle_data_from_card_creator(received_data)
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\Migaku Anki Extension\migaku_connection\card_creator.py", line 190, in handle_data_from_card_creator
    r = self._handle_data_from_card_creator(jsonData)
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\Migaku Anki Extension\migaku_connection\card_creator.py", line 242, in _handle_data_from_card_creator
    note.flush()
  File "anki\notes.py", line 81, in flush
AssertionError
ERROR:tornado.access:500 POST /create (127.0.0.1) 1.02ms
```

**Comment by RicBent** [comment]
Fixed with https://github.com/migaku-official/Migaku-Anki-Extension/commit/1f9c8d6e912f740b06c8f07a490ceacffef563c5
